sylius_grid:
    grids:
        app_admin_multinewsletter:
            driver:
                name: doctrine/orm
                options:
                    class: VladFilimon\MultiNewsletterPlugin\Entity\Newsletter
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                description:
                    type: string
                    label: sylius.ui.description
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
